# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mantra_hmi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(341, 406)
        Form.setMinimumSize(QtCore.QSize(324, 356))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.pushButton7_2 = QtGui.QPushButton(Form)
        self.pushButton7_2.setGeometry(QtCore.QRect(250, 233, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_2.setFont(font)
        self.pushButton7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_2.setObjectName(_fromUtf8("pushButton7_2"))
        self.pushButton2_2 = QtGui.QPushButton(Form)
        self.pushButton2_2.setGeometry(QtCore.QRect(250, 43, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_2.setObjectName(_fromUtf8("pushButton2_2"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(8, 194, 130, 32))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton1_1 = QtGui.QPushButton(Form)
        self.pushButton1_1.setGeometry(QtCore.QRect(150, 5, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_1.setFont(font)
        self.pushButton1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_1.setObjectName(_fromUtf8("pushButton1_1"))
        self.pushButton3_1 = QtGui.QPushButton(Form)
        self.pushButton3_1.setGeometry(QtCore.QRect(150, 81, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_1.setFont(font)
        self.pushButton3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_1.setObjectName(_fromUtf8("pushButton3_1"))
        self.pushButton6_2 = QtGui.QPushButton(Form)
        self.pushButton6_2.setGeometry(QtCore.QRect(250, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_2.setFont(font)
        self.pushButton6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_2.setObjectName(_fromUtf8("pushButton6_2"))
        self.pushButton2_1 = QtGui.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(150, 43, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_1.setFont(font)
        self.pushButton2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_1.setObjectName(_fromUtf8("pushButton2_1"))
        self.pushButton7_1 = QtGui.QPushButton(Form)
        self.pushButton7_1.setGeometry(QtCore.QRect(150, 233, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_1.setFont(font)
        self.pushButton7_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_1.setObjectName(_fromUtf8("pushButton7_1"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(8, 156, 130, 32))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(8, 42, 130, 32))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton3_2 = QtGui.QPushButton(Form)
        self.pushButton3_2.setGeometry(QtCore.QRect(250, 81, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_2.setFont(font)
        self.pushButton3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_2.setObjectName(_fromUtf8("pushButton3_2"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(8, 118, 130, 32))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_1 = QtGui.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(8, 4, 130, 32))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.pushButton6_1 = QtGui.QPushButton(Form)
        self.pushButton6_1.setGeometry(QtCore.QRect(150, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_1.setFont(font)
        self.pushButton6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_1.setObjectName(_fromUtf8("pushButton6_1"))
        self.pushButton5_2 = QtGui.QPushButton(Form)
        self.pushButton5_2.setGeometry(QtCore.QRect(250, 157, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_2.setFont(font)
        self.pushButton5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_2.setObjectName(_fromUtf8("pushButton5_2"))
        self.pushButton4_2 = QtGui.QPushButton(Form)
        self.pushButton4_2.setGeometry(QtCore.QRect(250, 119, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_2.setFont(font)
        self.pushButton4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_2.setObjectName(_fromUtf8("pushButton4_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(8, 80, 130, 32))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton5_1 = QtGui.QPushButton(Form)
        self.pushButton5_1.setGeometry(QtCore.QRect(150, 157, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_1.setObjectName(_fromUtf8("pushButton5_1"))
        self.pushButton1_2 = QtGui.QPushButton(Form)
        self.pushButton1_2.setGeometry(QtCore.QRect(250, 5, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setObjectName(_fromUtf8("pushButton1_2"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(8, 232, 130, 32))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton4_1 = QtGui.QPushButton(Form)
        self.pushButton4_1.setGeometry(QtCore.QRect(150, 119, 85, 34))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_1.setFont(font)
        self.pushButton4_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_1.setObjectName(_fromUtf8("pushButton4_1"))
        self.saveButton = QtGui.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(8, 310, 96, 40))
        self.saveButton.setMinimumSize(QtCore.QSize(96, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(120, 120))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.powerButton = QtGui.QPushButton(Form)
        self.powerButton.setGeometry(QtCore.QRect(214, 310, 120, 90))
        self.powerButton.setMinimumSize(QtCore.QSize(30, 30))
        self.powerButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.powerButton.setFont(font)
        self.powerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerButton.setObjectName(_fromUtf8("powerButton"))
        self.resetButton = QtGui.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(110, 310, 96, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(120, 120))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalSlider = QtGui.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(95, 272, 115, 32))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(8)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(8, 272, 91, 32))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(250, 272, 85, 32))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(216, 272, 31, 32))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.setHomeButton = QtGui.QPushButton(Form)
        self.setHomeButton.setGeometry(QtCore.QRect(110, 360, 96, 40))
        self.setHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.setHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.setHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setHomeButton.setObjectName(_fromUtf8("setHomeButton"))
        self.backHomeButton = QtGui.QPushButton(Form)
        self.backHomeButton.setGeometry(QtCore.QRect(8, 360, 96, 40))
        self.backHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.backHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.backHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backHomeButton.setObjectName(_fromUtf8("backHomeButton"))

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.pushButton1_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint1_minus)
        QtCore.QObject.connect(self.pushButton1_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint1_plus)
        QtCore.QObject.connect(self.powerButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.power)
        QtCore.QObject.connect(self.pushButton2_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint2_minus)
        QtCore.QObject.connect(self.pushButton2_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint2_plus)
        QtCore.QObject.connect(self.pushButton3_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint3_minus)
        QtCore.QObject.connect(self.pushButton3_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint3_plus)
        QtCore.QObject.connect(self.pushButton4_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint4_minus)
        QtCore.QObject.connect(self.pushButton4_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint4_plus)
        QtCore.QObject.connect(self.pushButton5_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint5_minus)
        QtCore.QObject.connect(self.pushButton5_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint5_plus)
        QtCore.QObject.connect(self.pushButton6_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint6_minus)
        QtCore.QObject.connect(self.pushButton6_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint6_plus)
        QtCore.QObject.connect(self.pushButton7_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint7_minus)
        QtCore.QObject.connect(self.pushButton7_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint7_plus)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.save_state)
        QtCore.QObject.connect(self.pushButton1_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint1_minus_done)
        QtCore.QObject.connect(self.pushButton1_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint1_plus_done)
        QtCore.QObject.connect(self.pushButton2_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint2_minus_done)
        QtCore.QObject.connect(self.pushButton2_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint2_plus_done)
        QtCore.QObject.connect(self.pushButton3_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint3_minus_done)
        QtCore.QObject.connect(self.pushButton3_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint3_plus_done)
        QtCore.QObject.connect(self.pushButton4_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint4_minus_done)
        QtCore.QObject.connect(self.pushButton4_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint4_plus_done)
        QtCore.QObject.connect(self.pushButton5_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint5_minus_done)
        QtCore.QObject.connect(self.pushButton5_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint5_plus_done)
        QtCore.QObject.connect(self.pushButton6_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint6_minus_done)
        QtCore.QObject.connect(self.pushButton6_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint6_plus_done)
        QtCore.QObject.connect(self.pushButton7_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint7_minus_done)
        QtCore.QObject.connect(self.pushButton7_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint7_plus_done)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.slide_moved)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.reset_arm)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Form.selectionchange)
        QtCore.QObject.connect(self.setHomeButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.set_home)
        QtCore.QObject.connect(self.backHomeButton, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.back_home)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton1_1, self.pushButton1_2)
        Form.setTabOrder(self.pushButton1_2, self.pushButton2_1)
        Form.setTabOrder(self.pushButton2_1, self.pushButton2_2)
        Form.setTabOrder(self.pushButton2_2, self.pushButton3_1)
        Form.setTabOrder(self.pushButton3_1, self.pushButton3_2)
        Form.setTabOrder(self.pushButton3_2, self.pushButton4_1)
        Form.setTabOrder(self.pushButton4_1, self.pushButton4_2)
        Form.setTabOrder(self.pushButton4_2, self.pushButton5_1)
        Form.setTabOrder(self.pushButton5_1, self.pushButton5_2)
        Form.setTabOrder(self.pushButton5_2, self.pushButton6_1)
        Form.setTabOrder(self.pushButton6_1, self.pushButton6_2)
        Form.setTabOrder(self.pushButton6_2, self.pushButton7_1)
        Form.setTabOrder(self.pushButton7_1, self.pushButton7_2)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Mantra HMI", None))
        self.pushButton7_2.setText(_translate("Form", "+", None))
        self.pushButton2_2.setText(_translate("Form", "+", None))
        self.label_6.setText(_translate("Form", "Joint6 ( 0.000 rad )", None))
        self.pushButton1_1.setText(_translate("Form", "-", None))
        self.pushButton3_1.setText(_translate("Form", "-", None))
        self.pushButton6_2.setText(_translate("Form", "+", None))
        self.pushButton2_1.setText(_translate("Form", "-", None))
        self.pushButton7_1.setText(_translate("Form", "-", None))
        self.label_5.setText(_translate("Form", "Joint5 ( 0.000 rad )", None))
        self.label_2.setText(_translate("Form", "Joint2 ( 0.000 rad )", None))
        self.pushButton3_2.setText(_translate("Form", "+", None))
        self.label_4.setText(_translate("Form", "Joint4 ( 0.000 rad )", None))
        self.label_1.setText(_translate("Form", "Joint1 ( 0.000 rad )", None))
        self.pushButton6_1.setText(_translate("Form", "-", None))
        self.pushButton5_2.setText(_translate("Form", "+", None))
        self.pushButton4_2.setText(_translate("Form", "+", None))
        self.label_3.setText(_translate("Form", "Joint3 ( 0.000 rad )", None))
        self.pushButton5_1.setText(_translate("Form", "-", None))
        self.pushButton1_2.setText(_translate("Form", "+", None))
        self.label_7.setText(_translate("Form", "Joint7 ( 0.000 rad )", None))
        self.pushButton4_1.setText(_translate("Form", "-", None))
        self.saveButton.setText(_translate("Form", "Save States", None))
        self.powerButton.setText(_translate("Form", "Power OFF", None))
        self.resetButton.setText(_translate("Form", "Reset Arm", None))
        self.label_8.setText(_translate("Form", "Speed 50%", None))
        self.comboBox.setItemText(0, _translate("Form", "90.0 deg", None))
        self.comboBox.setItemText(1, _translate("Form", "60.0 deg", None))
        self.comboBox.setItemText(2, _translate("Form", "30.0 deg", None))
        self.comboBox.setItemText(3, _translate("Form", "10.0 deg", None))
        self.comboBox.setItemText(4, _translate("Form", "5.00 deg", None))
        self.comboBox.setItemText(5, _translate("Form", "1.00 deg", None))
        self.comboBox.setItemText(6, _translate("Form", "0.50 deg", None))
        self.comboBox.setItemText(7, _translate("Form", "0.25 deg", None))
        self.comboBox.setItemText(8, _translate("Form", "0.10 deg", None))
        self.comboBox.setItemText(9, _translate("Form", "0.05 deg", None))
        self.comboBox.setItemText(10, _translate("Form", "1.60 rad", None))
        self.comboBox.setItemText(11, _translate("Form", "0.80 rad", None))
        self.comboBox.setItemText(12, _translate("Form", "0.40 rad", None))
        self.comboBox.setItemText(13, _translate("Form", "0.20 rad", None))
        self.comboBox.setItemText(14, _translate("Form", "0.10 rad", None))
        self.comboBox.setItemText(15, _translate("Form", "0.05 rad", None))
        self.comboBox.setItemText(16, _translate("Form", "0.02 rad", None))
        self.comboBox.setItemText(17, _translate("Form", "0.01 rad", None))
        self.label_9.setText(_translate("Form", "Step", None))
        self.setHomeButton.setText(_translate("Form", "Set Home", None))
        self.backHomeButton.setText(_translate("Form", "Back Home", None))

