# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mantra_hmi_pro.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 406)
        Form.setMinimumSize(QtCore.QSize(324, 356))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.pushButton7_2 = QtWidgets.QPushButton(Form)
        self.pushButton7_2.setGeometry(QtCore.QRect(250, 233, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_2.setFont(font)
        self.pushButton7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_2.setObjectName("pushButton7_2")
        self.pushButton2_2 = QtWidgets.QPushButton(Form)
        self.pushButton2_2.setGeometry(QtCore.QRect(250, 43, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(8, 194, 140, 32))
        self.label_6.setObjectName("label_6")
        self.pushButton1_1 = QtWidgets.QPushButton(Form)
        self.pushButton1_1.setGeometry(QtCore.QRect(154, 5, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_1.setFont(font)
        self.pushButton1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pushButton3_1 = QtWidgets.QPushButton(Form)
        self.pushButton3_1.setGeometry(QtCore.QRect(154, 81, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_1.setFont(font)
        self.pushButton3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_1.setObjectName("pushButton3_1")
        self.pushButton6_2 = QtWidgets.QPushButton(Form)
        self.pushButton6_2.setGeometry(QtCore.QRect(250, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_2.setFont(font)
        self.pushButton6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_2.setObjectName("pushButton6_2")
        self.pushButton2_1 = QtWidgets.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(154, 43, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_1.setFont(font)
        self.pushButton2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton7_1 = QtWidgets.QPushButton(Form)
        self.pushButton7_1.setGeometry(QtCore.QRect(154, 233, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_1.setFont(font)
        self.pushButton7_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_1.setObjectName("pushButton7_1")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(8, 156, 140, 32))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(8, 42, 140, 32))
        self.label_2.setObjectName("label_2")
        self.pushButton3_2 = QtWidgets.QPushButton(Form)
        self.pushButton3_2.setGeometry(QtCore.QRect(250, 81, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_2.setFont(font)
        self.pushButton3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_2.setObjectName("pushButton3_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(8, 118, 140, 32))
        self.label_4.setObjectName("label_4")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(8, 4, 140, 32))
        self.label_1.setObjectName("label_1")
        self.pushButton6_1 = QtWidgets.QPushButton(Form)
        self.pushButton6_1.setGeometry(QtCore.QRect(154, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_1.setFont(font)
        self.pushButton6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_1.setObjectName("pushButton6_1")
        self.pushButton5_2 = QtWidgets.QPushButton(Form)
        self.pushButton5_2.setGeometry(QtCore.QRect(250, 157, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_2.setFont(font)
        self.pushButton5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_2.setObjectName("pushButton5_2")
        self.pushButton4_2 = QtWidgets.QPushButton(Form)
        self.pushButton4_2.setGeometry(QtCore.QRect(250, 119, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_2.setFont(font)
        self.pushButton4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(8, 80, 140, 32))
        self.label_3.setObjectName("label_3")
        self.pushButton5_1 = QtWidgets.QPushButton(Form)
        self.pushButton5_1.setGeometry(QtCore.QRect(154, 157, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_1.setObjectName("pushButton5_1")
        self.pushButton1_2 = QtWidgets.QPushButton(Form)
        self.pushButton1_2.setGeometry(QtCore.QRect(250, 5, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(8, 232, 140, 32))
        self.label_7.setObjectName("label_7")
        self.pushButton4_1 = QtWidgets.QPushButton(Form)
        self.pushButton4_1.setGeometry(QtCore.QRect(154, 119, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_1.setFont(font)
        self.pushButton4_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_1.setObjectName("pushButton4_1")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(8, 360, 96, 40))
        self.saveButton.setMinimumSize(QtCore.QSize(96, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(120, 120))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.powerButton = QtWidgets.QPushButton(Form)
        self.powerButton.setGeometry(QtCore.QRect(215, 310, 120, 40))
        self.powerButton.setMinimumSize(QtCore.QSize(30, 30))
        self.powerButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.powerButton.setFont(font)
        self.powerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerButton.setObjectName("powerButton")
        self.resetButton = QtWidgets.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(8, 310, 96, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(120, 120))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(88, 275, 76, 28))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(8)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(8, 272, 81, 32))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(250, 275, 85, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(216, 272, 31, 32))
        self.label_9.setObjectName("label_9")
        self.setHomeButton = QtWidgets.QPushButton(Form)
        self.setHomeButton.setGeometry(QtCore.QRect(110, 310, 96, 40))
        self.setHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.setHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.setHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setHomeButton.setObjectName("setHomeButton")
        self.backHomeButton = QtWidgets.QPushButton(Form)
        self.backHomeButton.setGeometry(QtCore.QRect(110, 360, 96, 40))
        self.backHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.backHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.backHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backHomeButton.setObjectName("backHomeButton")
        self.radDegButton = QtWidgets.QPushButton(Form)
        self.radDegButton.setGeometry(QtCore.QRect(169, 275, 42, 28))
        self.radDegButton.setObjectName("radDegButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(215, 360, 120, 40))
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setObjectName("stopButton")

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(3)
        self.pushButton1_1.pressed.connect(Form.joint1_minus)
        self.pushButton1_2.pressed.connect(Form.joint1_plus)
        self.powerButton.pressed.connect(Form.power)
        self.pushButton2_1.pressed.connect(Form.joint2_minus)
        self.pushButton2_2.pressed.connect(Form.joint2_plus)
        self.pushButton3_1.pressed.connect(Form.joint3_minus)
        self.pushButton3_2.pressed.connect(Form.joint3_plus)
        self.pushButton4_1.pressed.connect(Form.joint4_minus)
        self.pushButton4_2.pressed.connect(Form.joint4_plus)
        self.pushButton5_1.pressed.connect(Form.joint5_minus)
        self.pushButton5_2.pressed.connect(Form.joint5_plus)
        self.pushButton6_1.pressed.connect(Form.joint6_minus)
        self.pushButton6_2.pressed.connect(Form.joint6_plus)
        self.pushButton7_1.pressed.connect(Form.joint7_minus)
        self.pushButton7_2.pressed.connect(Form.joint7_plus)
        self.saveButton.pressed.connect(Form.save_state)
        self.pushButton1_1.released.connect(Form.joint1_minus_done)
        self.pushButton1_2.released.connect(Form.joint1_plus_done)
        self.pushButton2_1.released.connect(Form.joint2_minus_done)
        self.pushButton2_2.released.connect(Form.joint2_plus_done)
        self.pushButton3_1.released.connect(Form.joint3_minus_done)
        self.pushButton3_2.released.connect(Form.joint3_plus_done)
        self.pushButton4_1.released.connect(Form.joint4_minus_done)
        self.pushButton4_2.released.connect(Form.joint4_plus_done)
        self.pushButton5_1.released.connect(Form.joint5_minus_done)
        self.pushButton5_2.released.connect(Form.joint5_plus_done)
        self.pushButton6_1.released.connect(Form.joint6_minus_done)
        self.pushButton6_2.released.connect(Form.joint6_plus_done)
        self.pushButton7_1.released.connect(Form.joint7_minus_done)
        self.pushButton7_2.released.connect(Form.joint7_plus_done)
        self.horizontalSlider.valueChanged['int'].connect(Form.slide_moved)
        self.resetButton.pressed.connect(Form.reset_arm)
        self.comboBox.currentIndexChanged['int'].connect(Form.selectionchange)
        self.setHomeButton.pressed.connect(Form.set_home)
        self.backHomeButton.pressed.connect(Form.back_home)
        self.radDegButton.pressed.connect(Form.rad_deg)
        self.stopButton.released.connect(Form.emergency_stop)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton1_1, self.pushButton1_2)
        Form.setTabOrder(self.pushButton1_2, self.pushButton2_1)
        Form.setTabOrder(self.pushButton2_1, self.pushButton2_2)
        Form.setTabOrder(self.pushButton2_2, self.pushButton3_1)
        Form.setTabOrder(self.pushButton3_1, self.pushButton3_2)
        Form.setTabOrder(self.pushButton3_2, self.pushButton4_1)
        Form.setTabOrder(self.pushButton4_1, self.pushButton4_2)
        Form.setTabOrder(self.pushButton4_2, self.pushButton5_1)
        Form.setTabOrder(self.pushButton5_1, self.pushButton5_2)
        Form.setTabOrder(self.pushButton5_2, self.pushButton6_1)
        Form.setTabOrder(self.pushButton6_1, self.pushButton6_2)
        Form.setTabOrder(self.pushButton6_2, self.pushButton7_1)
        Form.setTabOrder(self.pushButton7_1, self.pushButton7_2)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mantra HMI"))
        self.pushButton7_2.setText(_translate("Form", "+"))
        self.pushButton2_2.setText(_translate("Form", "+"))
        self.label_6.setText(_translate("Form", "Joint6 ( 0.000 rad )"))
        self.pushButton1_1.setText(_translate("Form", "-"))
        self.pushButton3_1.setText(_translate("Form", "-"))
        self.pushButton6_2.setText(_translate("Form", "+"))
        self.pushButton2_1.setText(_translate("Form", "-"))
        self.pushButton7_1.setText(_translate("Form", "-"))
        self.label_5.setText(_translate("Form", "Joint5 ( 0.000 rad )"))
        self.label_2.setText(_translate("Form", "Joint2 ( 0.000 rad )"))
        self.pushButton3_2.setText(_translate("Form", "+"))
        self.label_4.setText(_translate("Form", "Joint4 ( 0.000 rad )"))
        self.label_1.setText(_translate("Form", "Joint1 ( 0.000 rad )"))
        self.pushButton6_1.setText(_translate("Form", "-"))
        self.pushButton5_2.setText(_translate("Form", "+"))
        self.pushButton4_2.setText(_translate("Form", "+"))
        self.label_3.setText(_translate("Form", "Joint3 ( 0.000 rad )"))
        self.pushButton5_1.setText(_translate("Form", "-"))
        self.pushButton1_2.setText(_translate("Form", "+"))
        self.label_7.setText(_translate("Form", "Joint7 ( 0.000 rad )"))
        self.pushButton4_1.setText(_translate("Form", "-"))
        self.saveButton.setText(_translate("Form", "Save States"))
        self.powerButton.setText(_translate("Form", "Power OFF"))
        self.resetButton.setText(_translate("Form", "Reset Arm"))
        self.label_8.setText(_translate("Form", "Speed 50%"))
        self.comboBox.setItemText(0, _translate("Form", "90.0 deg"))
        self.comboBox.setItemText(1, _translate("Form", "60.0 deg"))
        self.comboBox.setItemText(2, _translate("Form", "30.0 deg"))
        self.comboBox.setItemText(3, _translate("Form", "10.0 deg"))
        self.comboBox.setItemText(4, _translate("Form", "5.00 deg"))
        self.comboBox.setItemText(5, _translate("Form", "1.00 deg"))
        self.comboBox.setItemText(6, _translate("Form", "0.50 deg"))
        self.comboBox.setItemText(7, _translate("Form", "0.25 deg"))
        self.comboBox.setItemText(8, _translate("Form", "0.10 deg"))
        self.comboBox.setItemText(9, _translate("Form", "0.05 deg"))
        self.comboBox.setItemText(10, _translate("Form", "1.60 rad"))
        self.comboBox.setItemText(11, _translate("Form", "0.80 rad"))
        self.comboBox.setItemText(12, _translate("Form", "0.40 rad"))
        self.comboBox.setItemText(13, _translate("Form", "0.20 rad"))
        self.comboBox.setItemText(14, _translate("Form", "0.10 rad"))
        self.comboBox.setItemText(15, _translate("Form", "0.05 rad"))
        self.comboBox.setItemText(16, _translate("Form", "0.02 rad"))
        self.comboBox.setItemText(17, _translate("Form", "0.01 rad"))
        self.label_9.setText(_translate("Form", "Step"))
        self.setHomeButton.setText(_translate("Form", "Set Home"))
        self.backHomeButton.setText(_translate("Form", "Back Home"))
        self.radDegButton.setText(_translate("Form", "deg"))
        self.stopButton.setText(_translate("Form", "Emergency"))

