# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mantra_hmi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(324, 356)
        Form.setMinimumSize(QtCore.QSize(324, 356))
        Form.setMaximumSize(QtCore.QSize(324, 356))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.pushButton7_2 = QtGui.QPushButton(Form)
        self.pushButton7_2.setGeometry(QtCore.QRect(230, 234, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_2.setFont(font)
        self.pushButton7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_2.setObjectName(_fromUtf8("pushButton7_2"))
        self.pushButton2_2 = QtGui.QPushButton(Form)
        self.pushButton2_2.setGeometry(QtCore.QRect(230, 44, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_2.setObjectName(_fromUtf8("pushButton2_2"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(9, 194, 118, 32))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton1_1 = QtGui.QPushButton(Form)
        self.pushButton1_1.setGeometry(QtCore.QRect(139, 6, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_1.setFont(font)
        self.pushButton1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_1.setObjectName(_fromUtf8("pushButton1_1"))
        self.pushButton3_1 = QtGui.QPushButton(Form)
        self.pushButton3_1.setGeometry(QtCore.QRect(139, 82, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_1.setFont(font)
        self.pushButton3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_1.setObjectName(_fromUtf8("pushButton3_1"))
        self.pushButton6_2 = QtGui.QPushButton(Form)
        self.pushButton6_2.setGeometry(QtCore.QRect(230, 196, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_2.setFont(font)
        self.pushButton6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_2.setObjectName(_fromUtf8("pushButton6_2"))
        self.pushButton2_1 = QtGui.QPushButton(Form)
        self.pushButton2_1.setGeometry(QtCore.QRect(139, 44, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_1.setFont(font)
        self.pushButton2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_1.setObjectName(_fromUtf8("pushButton2_1"))
        self.pushButton7_1 = QtGui.QPushButton(Form)
        self.pushButton7_1.setGeometry(QtCore.QRect(139, 234, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_1.setFont(font)
        self.pushButton7_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_1.setObjectName(_fromUtf8("pushButton7_1"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(9, 156, 118, 32))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(9, 42, 118, 32))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton3_2 = QtGui.QPushButton(Form)
        self.pushButton3_2.setGeometry(QtCore.QRect(230, 82, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_2.setFont(font)
        self.pushButton3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_2.setObjectName(_fromUtf8("pushButton3_2"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(9, 118, 118, 32))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_1 = QtGui.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(9, 4, 118, 32))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.pushButton6_1 = QtGui.QPushButton(Form)
        self.pushButton6_1.setGeometry(QtCore.QRect(139, 196, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_1.setFont(font)
        self.pushButton6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_1.setObjectName(_fromUtf8("pushButton6_1"))
        self.pushButton5_2 = QtGui.QPushButton(Form)
        self.pushButton5_2.setGeometry(QtCore.QRect(230, 158, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_2.setFont(font)
        self.pushButton5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_2.setObjectName(_fromUtf8("pushButton5_2"))
        self.pushButton4_2 = QtGui.QPushButton(Form)
        self.pushButton4_2.setGeometry(QtCore.QRect(230, 120, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_2.setFont(font)
        self.pushButton4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_2.setObjectName(_fromUtf8("pushButton4_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(9, 80, 118, 32))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton5_1 = QtGui.QPushButton(Form)
        self.pushButton5_1.setGeometry(QtCore.QRect(139, 158, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_1.setObjectName(_fromUtf8("pushButton5_1"))
        self.pushButton1_2 = QtGui.QPushButton(Form)
        self.pushButton1_2.setGeometry(QtCore.QRect(230, 6, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setObjectName(_fromUtf8("pushButton1_2"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(9, 232, 118, 32))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton4_1 = QtGui.QPushButton(Form)
        self.pushButton4_1.setGeometry(QtCore.QRect(139, 120, 85, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_1.setFont(font)
        self.pushButton4_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_1.setObjectName(_fromUtf8("pushButton4_1"))
        self.resetButton = QtGui.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(114, 310, 96, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(90, 50))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.finetuneButton = QtGui.QPushButton(Form)
        self.finetuneButton.setGeometry(QtCore.QRect(8, 310, 96, 40))
        self.finetuneButton.setMinimumSize(QtCore.QSize(96, 30))
        self.finetuneButton.setMaximumSize(QtCore.QSize(90, 50))
        self.finetuneButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finetuneButton.setObjectName(_fromUtf8("finetuneButton"))
        self.resetButton_2 = QtGui.QPushButton(Form)
        self.resetButton_2.setGeometry(QtCore.QRect(220, 310, 96, 40))
        self.resetButton_2.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton_2.setMaximumSize(QtCore.QSize(90, 50))
        self.resetButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton_2.setObjectName(_fromUtf8("resetButton_2"))
        self.horizontalSlider = QtGui.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(140, 270, 171, 32))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(8)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 270, 131, 32))
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton1_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint1_minus)
        QtCore.QObject.connect(self.pushButton1_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint1_plus)
        QtCore.QObject.connect(self.finetuneButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.fine_tuning)
        QtCore.QObject.connect(self.pushButton2_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint2_minus)
        QtCore.QObject.connect(self.pushButton2_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint2_plus)
        QtCore.QObject.connect(self.pushButton3_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint3_minus)
        QtCore.QObject.connect(self.pushButton3_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint3_plus)
        QtCore.QObject.connect(self.pushButton4_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint4_minus)
        QtCore.QObject.connect(self.pushButton4_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint4_plus)
        QtCore.QObject.connect(self.pushButton5_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint5_minus)
        QtCore.QObject.connect(self.pushButton5_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint5_plus)
        QtCore.QObject.connect(self.pushButton6_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint6_minus)
        QtCore.QObject.connect(self.pushButton6_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint6_plus)
        QtCore.QObject.connect(self.pushButton7_1, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint7_minus)
        QtCore.QObject.connect(self.pushButton7_2, QtCore.SIGNAL(_fromUtf8("pressed()")), Form.joint7_plus)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.save_state)
        QtCore.QObject.connect(self.pushButton1_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint1_minus_done)
        QtCore.QObject.connect(self.pushButton1_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint1_plus_done)
        QtCore.QObject.connect(self.pushButton2_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint2_minus_done)
        QtCore.QObject.connect(self.pushButton2_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint2_plus_done)
        QtCore.QObject.connect(self.pushButton3_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint3_minus_done)
        QtCore.QObject.connect(self.pushButton3_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint3_plus_done)
        QtCore.QObject.connect(self.pushButton4_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint4_minus_done)
        QtCore.QObject.connect(self.pushButton4_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint4_plus_done)
        QtCore.QObject.connect(self.pushButton5_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint5_minus_done)
        QtCore.QObject.connect(self.pushButton5_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint5_plus_done)
        QtCore.QObject.connect(self.pushButton6_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint6_minus_done)
        QtCore.QObject.connect(self.pushButton6_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint6_plus_done)
        QtCore.QObject.connect(self.pushButton7_1, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint7_minus_done)
        QtCore.QObject.connect(self.pushButton7_2, QtCore.SIGNAL(_fromUtf8("released()")), Form.joint7_plus_done)
        QtCore.QObject.connect(self.horizontalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Form.slide_moved)
        QtCore.QObject.connect(self.resetButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.reset_robot)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton1_1, self.pushButton1_2)
        Form.setTabOrder(self.pushButton1_2, self.pushButton2_1)
        Form.setTabOrder(self.pushButton2_1, self.pushButton2_2)
        Form.setTabOrder(self.pushButton2_2, self.pushButton3_1)
        Form.setTabOrder(self.pushButton3_1, self.pushButton3_2)
        Form.setTabOrder(self.pushButton3_2, self.pushButton4_1)
        Form.setTabOrder(self.pushButton4_1, self.pushButton4_2)
        Form.setTabOrder(self.pushButton4_2, self.pushButton5_1)
        Form.setTabOrder(self.pushButton5_1, self.pushButton5_2)
        Form.setTabOrder(self.pushButton5_2, self.pushButton6_1)
        Form.setTabOrder(self.pushButton6_1, self.pushButton6_2)
        Form.setTabOrder(self.pushButton6_2, self.pushButton7_1)
        Form.setTabOrder(self.pushButton7_1, self.pushButton7_2)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Mantra HMI", None))
        self.pushButton7_2.setText(_translate("Form", "+", None))
        self.pushButton2_2.setText(_translate("Form", "+", None))
        self.label_6.setText(_translate("Form", "Joint6 ( 0.00 rad )", None))
        self.pushButton1_1.setText(_translate("Form", "-", None))
        self.pushButton3_1.setText(_translate("Form", "-", None))
        self.pushButton6_2.setText(_translate("Form", "+", None))
        self.pushButton2_1.setText(_translate("Form", "-", None))
        self.pushButton7_1.setText(_translate("Form", "-", None))
        self.label_5.setText(_translate("Form", "Joint5 ( 0.00 rad )", None))
        self.label_2.setText(_translate("Form", "Joint2 ( 0.00 rad )", None))
        self.pushButton3_2.setText(_translate("Form", "+", None))
        self.label_4.setText(_translate("Form", "Joint4 ( 0.00 rad )", None))
        self.label_1.setText(_translate("Form", "Joint1 ( 0.00 rad )", None))
        self.pushButton6_1.setText(_translate("Form", "-", None))
        self.pushButton5_2.setText(_translate("Form", "+", None))
        self.pushButton4_2.setText(_translate("Form", "+", None))
        self.label_3.setText(_translate("Form", "Joint3 ( 0.00 rad )", None))
        self.pushButton5_1.setText(_translate("Form", "-", None))
        self.pushButton1_2.setText(_translate("Form", "+", None))
        self.label_7.setText(_translate("Form", "Joint7 ( 0.00 rad )", None))
        self.pushButton4_1.setText(_translate("Form", "-", None))
        self.resetButton.setText(_translate("Form", "Save states", None))
        self.finetuneButton.setText(_translate("Form", "Fine tuning", None))
        self.resetButton_2.setText(_translate("Form", "Reset robot", None))
        self.label_8.setText(_translate("Form", "Speed Zoom 20%", None))

