controller_list:
  - name: fake_arm_controller
    joints:
      - base_joint
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_updown_controller
    joints:
      - base_joint