controller_list:
  - name: "mantra"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7

  - name: "mantra"
    action_ns: gripper_command
    type: GripperCommand
    default: true
    joints:
      - ee_joint1