# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mantra_hmi_pro.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(345, 455)
        Form.setMinimumSize(QtCore.QSize(324, 356))
        Form.setMaximumSize(QtCore.QSize(345, 455))
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(3, 413, 96, 40))
        self.saveButton.setMinimumSize(QtCore.QSize(96, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(120, 120))
        self.saveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveButton.setObjectName("saveButton")
        self.powerButton = QtWidgets.QPushButton(Form)
        self.powerButton.setGeometry(QtCore.QRect(223, 366, 120, 40))
        self.powerButton.setMinimumSize(QtCore.QSize(30, 30))
        self.powerButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.powerButton.setFont(font)
        self.powerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.powerButton.setObjectName("powerButton")
        self.resetButton = QtWidgets.QPushButton(Form)
        self.resetButton.setGeometry(QtCore.QRect(3, 366, 96, 40))
        self.resetButton.setMinimumSize(QtCore.QSize(96, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(120, 120))
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(100, 340, 234, 28))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setProperty("value", 50)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(8)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 337, 81, 32))
        self.label_8.setObjectName("label_8")
        self.setHomeButton = QtWidgets.QPushButton(Form)
        self.setHomeButton.setGeometry(QtCore.QRect(113, 366, 96, 40))
        self.setHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.setHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.setHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setHomeButton.setObjectName("setHomeButton")
        self.backHomeButton = QtWidgets.QPushButton(Form)
        self.backHomeButton.setGeometry(QtCore.QRect(113, 413, 96, 40))
        self.backHomeButton.setMinimumSize(QtCore.QSize(96, 30))
        self.backHomeButton.setMaximumSize(QtCore.QSize(120, 120))
        self.backHomeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backHomeButton.setObjectName("backHomeButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(223, 413, 120, 40))
        self.stopButton.setMinimumSize(QtCore.QSize(30, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stopButton.setFont(font)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopButton.setObjectName("stopButton")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(3, 3, 339, 338))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.radDegButton_1 = QtWidgets.QPushButton(self.tab1)
        self.radDegButton_1.setGeometry(QtCore.QRect(67, 269, 69, 29))
        self.radDegButton_1.setObjectName("radDegButton_1")
        self.label_7 = QtWidgets.QLabel(self.tab1)
        self.label_7.setGeometry(QtCore.QRect(4, 229, 143, 32))
        self.label_7.setObjectName("label_7")
        self.pushButton3_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton3_2.setGeometry(QtCore.QRect(246, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_2.setFont(font)
        self.pushButton3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_2.setObjectName("pushButton3_2")
        self.label_step_1 = QtWidgets.QLabel(self.tab1)
        self.label_step_1.setGeometry(QtCore.QRect(172, 266, 41, 32))
        self.label_step_1.setObjectName("label_step_1")
        self.pushButton5_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton5_1.setGeometry(QtCore.QRect(150, 154, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_1.setFont(font)
        self.pushButton5_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_1.setObjectName("pushButton5_1")
        self.pushButton6_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton6_2.setGeometry(QtCore.QRect(246, 192, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_2.setFont(font)
        self.pushButton6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_2.setObjectName("pushButton6_2")
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setGeometry(QtCore.QRect(4, 153, 143, 32))
        self.label_5.setObjectName("label_5")
        self.pushButton4_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton4_2.setGeometry(QtCore.QRect(246, 116, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_2.setFont(font)
        self.pushButton4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.comboBox = QtWidgets.QComboBox(self.tab1)
        self.comboBox.setGeometry(QtCore.QRect(212, 268, 85, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton5_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton5_2.setGeometry(QtCore.QRect(246, 154, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_2.setFont(font)
        self.pushButton5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_2.setObjectName("pushButton5_2")
        self.pushButton6_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton6_1.setGeometry(QtCore.QRect(150, 192, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_1.setFont(font)
        self.pushButton6_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_1.setObjectName("pushButton6_1")
        self.pushButton1_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton1_1.setGeometry(QtCore.QRect(150, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_1.setFont(font)
        self.pushButton1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pushButton7_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton7_1.setGeometry(QtCore.QRect(150, 230, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_1.setFont(font)
        self.pushButton7_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_1.setObjectName("pushButton7_1")
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setGeometry(QtCore.QRect(4, 191, 143, 32))
        self.label_6.setObjectName("label_6")
        self.pushButton1_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton1_2.setGeometry(QtCore.QRect(246, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton7_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton7_2.setGeometry(QtCore.QRect(246, 230, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_2.setFont(font)
        self.pushButton7_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_2.setObjectName("pushButton7_2")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(4, 115, 143, 32))
        self.label_4.setObjectName("label_4")
        self.pushButton2_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton2_1.setGeometry(QtCore.QRect(150, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_1.setFont(font)
        self.pushButton2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton2_2 = QtWidgets.QPushButton(self.tab1)
        self.pushButton2_2.setGeometry(QtCore.QRect(246, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_2.setFont(font)
        self.pushButton2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.pushButton4_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton4_1.setGeometry(QtCore.QRect(150, 116, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton4_1.setFont(font)
        self.pushButton4_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton4_1.setObjectName("pushButton4_1")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(4, 39, 143, 32))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(4, 77, 143, 32))
        self.label_3.setObjectName("label_3")
        self.label_1 = QtWidgets.QLabel(self.tab1)
        self.label_1.setGeometry(QtCore.QRect(4, 1, 143, 32))
        self.label_1.setObjectName("label_1")
        self.pushButton3_1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton3_1.setGeometry(QtCore.QRect(150, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_1.setFont(font)
        self.pushButton3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_1.setObjectName("pushButton3_1")
        self.label_18 = QtWidgets.QLabel(self.tab1)
        self.label_18.setGeometry(QtCore.QRect(30, 266, 41, 32))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.pushButton7_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton7_3.setGeometry(QtCore.QRect(150, 235, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_3.setFont(font)
        self.pushButton7_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_3.setObjectName("pushButton7_3")
        self.pushButton5_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton5_3.setGeometry(QtCore.QRect(150, 156, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_3.setFont(font)
        self.pushButton5_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_3.setObjectName("pushButton5_3")
        self.label_23 = QtWidgets.QLabel(self.tab2)
        self.label_23.setGeometry(QtCore.QRect(30, 269, 41, 32))
        self.label_23.setObjectName("label_23")
        self.label_step3 = QtWidgets.QLabel(self.tab2)
        self.label_step3.setGeometry(QtCore.QRect(172, 269, 41, 32))
        self.label_step3.setObjectName("label_step3")
        self.pushButton5_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton5_4.setGeometry(QtCore.QRect(246, 156, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton5_4.setFont(font)
        self.pushButton5_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton5_4.setObjectName("pushButton5_4")
        self.pushButton2_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton2_4.setGeometry(QtCore.QRect(246, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_4.setFont(font)
        self.pushButton2_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_4.setObjectName("pushButton2_4")
        self.pushButton6_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton6_4.setGeometry(QtCore.QRect(246, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_4.setFont(font)
        self.pushButton6_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_4.setObjectName("pushButton6_4")
        self.pushButton7_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton7_4.setGeometry(QtCore.QRect(246, 235, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton7_4.setFont(font)
        self.pushButton7_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton7_4.setObjectName("pushButton7_4")
        self.pushButton6_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton6_3.setGeometry(QtCore.QRect(150, 195, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton6_3.setFont(font)
        self.pushButton6_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton6_3.setObjectName("pushButton6_3")
        self.radDegButton_2 = QtWidgets.QPushButton(self.tab2)
        self.radDegButton_2.setGeometry(QtCore.QRect(67, 272, 69, 29))
        self.radDegButton_2.setObjectName("radDegButton_2")
        self.pushButton1_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton1_3.setGeometry(QtCore.QRect(150, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_3.setFont(font)
        self.pushButton1_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.pushButton1_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton1_4.setGeometry(QtCore.QRect(246, 2, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton1_4.setFont(font)
        self.pushButton1_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.label_9 = QtWidgets.QLabel(self.tab2)
        self.label_9.setGeometry(QtCore.QRect(4, 1, 143, 32))
        self.label_9.setObjectName("label_9")
        self.comboBox_rpy = QtWidgets.QComboBox(self.tab2)
        self.comboBox_rpy.setGeometry(QtCore.QRect(212, 271, 85, 30))
        self.comboBox_rpy.setObjectName("comboBox_rpy")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.comboBox_rpy.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab2)
        self.label_11.setGeometry(QtCore.QRect(4, 77, 143, 32))
        self.label_11.setObjectName("label_11")
        self.pushButton3_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton3_3.setGeometry(QtCore.QRect(150, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_3.setFont(font)
        self.pushButton3_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_3.setObjectName("pushButton3_3")
        self.pushButton3_4 = QtWidgets.QPushButton(self.tab2)
        self.pushButton3_4.setGeometry(QtCore.QRect(246, 78, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton3_4.setFont(font)
        self.pushButton3_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton3_4.setObjectName("pushButton3_4")
        self.label_12 = QtWidgets.QLabel(self.tab2)
        self.label_12.setGeometry(QtCore.QRect(4, 156, 143, 32))
        self.label_12.setObjectName("label_12")
        self.pushButton2_3 = QtWidgets.QPushButton(self.tab2)
        self.pushButton2_3.setGeometry(QtCore.QRect(150, 40, 85, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton2_3.setFont(font)
        self.pushButton2_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton2_3.setObjectName("pushButton2_3")
        self.label_10 = QtWidgets.QLabel(self.tab2)
        self.label_10.setGeometry(QtCore.QRect(4, 39, 143, 32))
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.tab2)
        self.label_13.setGeometry(QtCore.QRect(4, 194, 143, 32))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab2)
        self.label_14.setGeometry(QtCore.QRect(4, 232, 143, 32))
        self.label_14.setObjectName("label_14")
        self.label_step2 = QtWidgets.QLabel(self.tab2)
        self.label_step2.setGeometry(QtCore.QRect(172, 113, 41, 32))
        self.label_step2.setObjectName("label_step2")
        self.label_25 = QtWidgets.QLabel(self.tab2)
        self.label_25.setGeometry(QtCore.QRect(30, 113, 41, 32))
        self.label_25.setObjectName("label_25")
        self.mCmButton_1 = QtWidgets.QPushButton(self.tab2)
        self.mCmButton_1.setGeometry(QtCore.QRect(67, 116, 69, 29))
        self.mCmButton_1.setObjectName("mCmButton_1")
        self.comboBox_xyz = QtWidgets.QComboBox(self.tab2)
        self.comboBox_xyz.setGeometry(QtCore.QRect(212, 115, 85, 30))
        self.comboBox_xyz.setObjectName("comboBox_xyz")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.comboBox_xyz.addItem("")
        self.line = QtWidgets.QFrame(self.tab2)
        self.line.setGeometry(QtCore.QRect(32, 143, 265, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tab2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(3)
        self.comboBox_rpy.setCurrentIndex(3)
        self.comboBox_xyz.setCurrentIndex(3)
        self.powerButton.pressed.connect(Form.power)
        self.saveButton.pressed.connect(Form.save_state)
        self.horizontalSlider.valueChanged['int'].connect(Form.slide_moved)
        self.resetButton.pressed.connect(Form.reset_arm)
        self.setHomeButton.pressed.connect(Form.set_home)
        self.backHomeButton.pressed.connect(Form.back_home)
        self.stopButton.released.connect(Form.emergency_stop)
        self.pushButton1_1.pressed.connect(Form.joint1_minus)
        self.pushButton1_1.released.connect(Form.joint1_minus_done)
        self.pushButton1_2.pressed.connect(Form.joint1_plus)
        self.pushButton1_2.released.connect(Form.joint1_plus_done)
        self.pushButton2_1.pressed.connect(Form.joint2_minus)
        self.pushButton2_1.released.connect(Form.joint2_minus_done)
        self.pushButton2_2.pressed.connect(Form.joint2_plus)
        self.pushButton2_2.released.connect(Form.joint2_plus_done)
        self.pushButton3_1.pressed.connect(Form.joint3_minus)
        self.pushButton3_1.released.connect(Form.joint3_minus_done)
        self.pushButton3_2.pressed.connect(Form.joint3_plus)
        self.pushButton3_2.released.connect(Form.joint3_plus_done)
        self.pushButton4_1.pressed.connect(Form.joint4_minus)
        self.pushButton4_1.released.connect(Form.joint4_minus_done)
        self.pushButton4_2.pressed.connect(Form.joint4_plus)
        self.pushButton4_2.released.connect(Form.joint4_plus_done)
        self.pushButton5_1.pressed.connect(Form.joint5_minus)
        self.pushButton5_1.released.connect(Form.joint5_minus_done)
        self.pushButton5_2.pressed.connect(Form.joint5_plus)
        self.pushButton5_2.released.connect(Form.joint5_plus_done)
        self.pushButton6_1.pressed.connect(Form.joint6_minus)
        self.pushButton6_1.released.connect(Form.joint6_minus_done)
        self.pushButton6_2.pressed.connect(Form.joint6_plus)
        self.pushButton6_2.released.connect(Form.joint6_plus_done)
        self.pushButton7_1.pressed.connect(Form.joint7_minus)
        self.pushButton7_1.released.connect(Form.joint7_minus_done)
        self.pushButton7_2.pressed.connect(Form.joint7_plus)
        self.pushButton7_2.released.connect(Form.joint7_plus_done)
        self.pushButton1_3.pressed.connect(Form.x_minus)
        self.pushButton1_4.pressed.connect(Form.x_plus)
        self.pushButton2_3.pressed.connect(Form.y_minus)
        self.pushButton2_4.pressed.connect(Form.y_plus)
        self.pushButton3_3.pressed.connect(Form.z_minus)
        self.pushButton3_4.pressed.connect(Form.z_plus)
        self.pushButton5_3.pressed.connect(Form.roll_minus)
        self.pushButton5_4.pressed.connect(Form.roll_plus)
        self.pushButton6_3.pressed.connect(Form.pitch_minus)
        self.pushButton6_4.pressed.connect(Form.pitch_plus)
        self.pushButton7_3.pressed.connect(Form.yaw_minus)
        self.pushButton7_4.pressed.connect(Form.yaw_plus)
        self.comboBox_xyz.currentIndexChanged['int'].connect(Form.movexyz_step_change)
        self.comboBox_rpy.currentIndexChanged['int'].connect(Form.moverpy_step_change)
        self.comboBox.currentIndexChanged['int'].connect(Form.movej_step_change)
        self.radDegButton_1.pressed.connect(Form.movej_rad_deg)
        self.radDegButton_2.pressed.connect(Form.movel_rad_deg)
        self.mCmButton_1.pressed.connect(Form.movel_m_cm)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Mantra HMI"))
        self.saveButton.setText(_translate("Form", "Save States"))
        self.powerButton.setText(_translate("Form", "Power OFF"))
        self.resetButton.setText(_translate("Form", "Reset Arm"))
        self.label_8.setText(_translate("Form", "Speed 50%"))
        self.setHomeButton.setText(_translate("Form", "Set Home"))
        self.backHomeButton.setText(_translate("Form", "Back Home"))
        self.stopButton.setText(_translate("Form", "Emergency"))
        self.radDegButton_1.setText(_translate("Form", "deg"))
        self.label_7.setText(_translate("Form", "Joint7 ( 0.000 rad )"))
        self.pushButton3_2.setText(_translate("Form", "+"))
        self.label_step_1.setText(_translate("Form", "Step:"))
        self.pushButton5_1.setText(_translate("Form", "-"))
        self.pushButton6_2.setText(_translate("Form", "+"))
        self.label_5.setText(_translate("Form", "Joint5 ( 0.000 rad )"))
        self.pushButton4_2.setText(_translate("Form", "+"))
        self.comboBox.setItemText(0, _translate("Form", "90.0 deg"))
        self.comboBox.setItemText(1, _translate("Form", "60.0 deg"))
        self.comboBox.setItemText(2, _translate("Form", "30.0 deg"))
        self.comboBox.setItemText(3, _translate("Form", "10.0 deg"))
        self.comboBox.setItemText(4, _translate("Form", "5.00 deg"))
        self.comboBox.setItemText(5, _translate("Form", "1.00 deg"))
        self.comboBox.setItemText(6, _translate("Form", "0.50 deg"))
        self.comboBox.setItemText(7, _translate("Form", "0.25 deg"))
        self.comboBox.setItemText(8, _translate("Form", "0.10 deg"))
        self.comboBox.setItemText(9, _translate("Form", "0.05 deg"))
        self.comboBox.setItemText(10, _translate("Form", "1.60 rad"))
        self.comboBox.setItemText(11, _translate("Form", "0.80 rad"))
        self.comboBox.setItemText(12, _translate("Form", "0.40 rad"))
        self.comboBox.setItemText(13, _translate("Form", "0.20 rad"))
        self.comboBox.setItemText(14, _translate("Form", "0.10 rad"))
        self.comboBox.setItemText(15, _translate("Form", "0.05 rad"))
        self.comboBox.setItemText(16, _translate("Form", "0.02 rad"))
        self.comboBox.setItemText(17, _translate("Form", "0.01 rad"))
        self.pushButton5_2.setText(_translate("Form", "+"))
        self.pushButton6_1.setText(_translate("Form", "-"))
        self.pushButton1_1.setText(_translate("Form", "-"))
        self.pushButton7_1.setText(_translate("Form", "-"))
        self.label_6.setText(_translate("Form", "Joint6 ( 0.000 rad )"))
        self.pushButton1_2.setText(_translate("Form", "+"))
        self.pushButton7_2.setText(_translate("Form", "+"))
        self.label_4.setText(_translate("Form", "Joint4 ( 0.000 rad )"))
        self.pushButton2_1.setText(_translate("Form", "-"))
        self.pushButton2_2.setText(_translate("Form", "+"))
        self.pushButton4_1.setText(_translate("Form", "-"))
        self.label_2.setText(_translate("Form", "Joint2 ( 0.000 rad )"))
        self.label_3.setText(_translate("Form", "Joint3 ( 0.000 rad )"))
        self.label_1.setText(_translate("Form", "Joint1 ( 0.000 rad )"))
        self.pushButton3_1.setText(_translate("Form", "-"))
        self.label_18.setText(_translate("Form", "Unit:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Form", "               MoveJ                "))
        self.pushButton7_3.setText(_translate("Form", "-"))
        self.pushButton5_3.setText(_translate("Form", "-"))
        self.label_23.setText(_translate("Form", "Unit:"))
        self.label_step3.setText(_translate("Form", "Step:"))
        self.pushButton5_4.setText(_translate("Form", "+"))
        self.pushButton2_4.setText(_translate("Form", "+"))
        self.pushButton6_4.setText(_translate("Form", "+"))
        self.pushButton7_4.setText(_translate("Form", "+"))
        self.pushButton6_3.setText(_translate("Form", "-"))
        self.radDegButton_2.setText(_translate("Form", "deg"))
        self.pushButton1_3.setText(_translate("Form", "-"))
        self.pushButton1_4.setText(_translate("Form", "+"))
        self.label_9.setText(_translate("Form", "Pose X ( 0.000 m )"))
        self.comboBox_rpy.setItemText(0, _translate("Form", "60.0 deg"))
        self.comboBox_rpy.setItemText(1, _translate("Form", "30.0 deg"))
        self.comboBox_rpy.setItemText(2, _translate("Form", "10.0 deg"))
        self.comboBox_rpy.setItemText(3, _translate("Form", "5.00 deg"))
        self.comboBox_rpy.setItemText(4, _translate("Form", "1.00 deg"))
        self.comboBox_rpy.setItemText(5, _translate("Form", "0.50 deg"))
        self.comboBox_rpy.setItemText(6, _translate("Form", "0.10 deg"))
        self.comboBox_rpy.setItemText(7, _translate("Form", "0.80 rad"))
        self.comboBox_rpy.setItemText(8, _translate("Form", "0.40 rad"))
        self.comboBox_rpy.setItemText(9, _translate("Form", "0.20 rad"))
        self.comboBox_rpy.setItemText(10, _translate("Form", "0.10 rad"))
        self.comboBox_rpy.setItemText(11, _translate("Form", "0.05 rad"))
        self.comboBox_rpy.setItemText(12, _translate("Form", "0.02 rad"))
        self.label_11.setText(_translate("Form", "Pose Z ( 0.000 m )"))
        self.pushButton3_3.setText(_translate("Form", "-"))
        self.pushButton3_4.setText(_translate("Form", "+"))
        self.label_12.setText(_translate("Form", "Pose R ( 0.000 rad )"))
        self.pushButton2_3.setText(_translate("Form", "-"))
        self.label_10.setText(_translate("Form", "Pose Y ( 0.000 m )"))
        self.label_13.setText(_translate("Form", "Pose P ( 0.000 rad )"))
        self.label_14.setText(_translate("Form", "Pose Y ( 0.000 rad )"))
        self.label_step2.setText(_translate("Form", "Step:"))
        self.label_25.setText(_translate("Form", "Unit:"))
        self.mCmButton_1.setText(_translate("Form", "m"))
        self.comboBox_xyz.setItemText(0, _translate("Form", "0.20 m"))
        self.comboBox_xyz.setItemText(1, _translate("Form", "0.15 m"))
        self.comboBox_xyz.setItemText(2, _translate("Form", "0.10 m"))
        self.comboBox_xyz.setItemText(3, _translate("Form", "0.05 m"))
        self.comboBox_xyz.setItemText(4, _translate("Form", "0.02 m"))
        self.comboBox_xyz.setItemText(5, _translate("Form", "0.01 m"))
        self.comboBox_xyz.setItemText(6, _translate("Form", "20.0 cm"))
        self.comboBox_xyz.setItemText(7, _translate("Form", "15.0 cm"))
        self.comboBox_xyz.setItemText(8, _translate("Form", "10.0 cm"))
        self.comboBox_xyz.setItemText(9, _translate("Form", "5.00 cm"))
        self.comboBox_xyz.setItemText(10, _translate("Form", "2.00 cm"))
        self.comboBox_xyz.setItemText(11, _translate("Form", "1.00 cm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "                MoveL                "))

